/**:
    ros__parameters:
      video_device: "/dev/video1"
      framerate: 15.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      color_format: "yuv422p"
      image_width: 320
      image_height: 240
      camera_name: "test_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"